/** Few-shot examples for Gemini intent classification (spec v2). */
export function buildBookingIntentFewShotBlock() {
  return [
    'Exemple:',
    '',
    'Mesaj: "Buna ziua, as dori sa imi fac o programare la salonul dumneavoastra"',
    '→ {"intent": "general_booking_request", "service_mentioned": null, "existing_appointment_time": null, "requested_new_time": null, "sensitive_topic": false, "contains_complaint_or_feedback": false, "confidence": "high"}',
    '',
    'Mesaj: "aveti loc azi?"',
    '→ {"intent": "general_booking_request", "service_mentioned": null, "existing_appointment_time": null, "requested_new_time": null, "sensitive_topic": false, "contains_complaint_or_feedback": false, "confidence": "high"}',
    '',
    'Mesaj: "tuns barba"',
    '→ {"intent": "specific_service_request", "service_mentioned": "<serviciul potrivit din listă>", "existing_appointment_time": null, "requested_new_time": null, "sensitive_topic": false, "contains_complaint_or_feedback": false, "confidence": "high"}',
    '',
    'Mesaj: "ITP"',
    '→ {"intent": "specific_service_request", "service_mentioned": "<serviciul potrivit din listă>", "existing_appointment_time": null, "requested_new_time": null, "sensitive_topic": false, "contains_complaint_or_feedback": false, "confidence": "high"}',
    '',
    'Mesaj: "am si eu o programare vineri la 9:30 se poate mutam la ora 15"',
    '→ {"intent": "reschedule_request", "service_mentioned": null, "existing_appointment_time": "vineri 9:30", "requested_new_time": "ora 15", "sensitive_topic": false, "contains_complaint_or_feedback": false, "confidence": "high"}',
    '',
    'Mesaj: "anulati programarea mea de luni va rog"',
    '→ {"intent": "cancellation", "service_mentioned": null, "existing_appointment_time": "luni", "requested_new_time": null, "sensitive_topic": false, "contains_complaint_or_feedback": false, "confidence": "high"}',
    '',
    'Mesaj: "nu mai pot sa ajung"',
    '→ {"intent": "unable_to_attend", "service_mentioned": null, "existing_appointment_time": null, "requested_new_time": null, "sensitive_topic": false, "contains_complaint_or_feedback": false, "confidence": "high"}',
    '',
    'Mesaj: "pot sa intarzii 5 minute?"',
    '→ {"intent": "running_late", "service_mentioned": null, "existing_appointment_time": null, "requested_new_time": null, "sensitive_topic": false, "contains_complaint_or_feedback": false, "confidence": "high"}',
    '',
    'Mesaj: "o sa ma doara?"',
    '→ {"intent": "question", "service_mentioned": null, "existing_appointment_time": null, "requested_new_time": null, "sensitive_topic": true, "contains_complaint_or_feedback": false, "confidence": "high"}',
    '',
    'Mesaj: "faceti clatite?"',
    '→ {"intent": "off_topic", "service_mentioned": null, "existing_appointment_time": null, "requested_new_time": null, "sensitive_topic": false, "contains_complaint_or_feedback": false, "confidence": "high"}',
    '',
    'Mesaj: "ok, multumesc"',
    '→ {"intent": "chitchat", "service_mentioned": null, "existing_appointment_time": null, "requested_new_time": null, "sensitive_topic": false, "contains_complaint_or_feedback": false, "confidence": "high"}',
    '',
    'Mesaj: "nu e chiar ce mi-am dorit dar ramane asa"',
    '→ {"intent": "chitchat", "service_mentioned": null, "existing_appointment_time": null, "requested_new_time": null, "sensitive_topic": false, "contains_complaint_or_feedback": true, "confidence": "high"}',
    '',
    'Mesaj: "am vorbit cu patronul sa ma bagi la 09:00, stiu ca e ocupat slotul"',
    '→ {"intent": "special_request", "service_mentioned": null, "existing_appointment_time": null, "requested_new_time": "09:00", "sensitive_topic": false, "contains_complaint_or_feedback": false, "confidence": "high"}',
    '',
    'Mesaj: "as vrea o programare pt injectii cu botox" (serviciu absent din listă)',
    '→ {"intent": "specific_service_request", "service_mentioned": null, "existing_appointment_time": null, "requested_new_time": null, "sensitive_topic": false, "contains_complaint_or_feedback": false, "confidence": "low"}',
  ].join('\n');
}
